name: Pipeline CI Node.js

on:
  push: # corre em todos os pushes
    branches: ["**"]

jobs:
  bob:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Jest & ESLint
        uses: actions/setup-node@v3
      - run: npm install #instala dependências
      - run: npx prettier . --write #formata ficheiros
      - run: npm run test #testa código com o Jest
      - run: npx prettier . --check #confirma formatação
      - run: npm run lint #ESLint

  builder:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: [bob]

    steps:
      - uses: actions/checkout@v3
      - name: build
        uses: actions/setup-node@v3
      - run: npm install #instala dependências
      - run: npm run build #build
